package models

import "git.defalsify.org/vise.git/state"

const (
	USERFLAG_LANGUAGE_SET = iota + state.FLAG_USERSTART
	USERFLAG_ACCOUNT_CREATED
	USERFLAG_ACCOUNT_PENDING
	USERFLAG_ACCOUNT_SUCCESS
	USERFLAG_ACCOUNT_UNLOCKED
	USERFLAG_INVALID_RECIPIENT
	USERFLAG_INVALID_RECIPIENT_WITH_INVITE
	USERFLAG_INCORRECTPIN
	USERFLAG_UNLOCKFORUPDATE
	USERFLAG_INVALID_AMOUNT
	USERFLAG_QUERYPIN
	USERFLAG_VALIDPIN
	USERFLAG_PINMISMATCH
	USERFLAG_INCORRECTDATEFORMAT
	USERFLAG_ACCOUNT_CREATION_FAILED
)
