package models

import "git.defalsify.org/vise.git/state"

const (
	USERFLAG_LANGUAGE_SET = iota + state.FLAG_USERSTART
	USERFLAG_ACCOUNT_CREATED
	USERFLAG_ACCOUNT_CREATION_FAILED
	USERFLAG_ACCOUNT_PENDING
	USERFLAG_ACCOUNT_SUCCESS
	USERFLAG_PINMISMATCH
	USERFLAG_PIN_SET
	USERFLAG_ACCOUNT_AUTHORIZED
	USERFLAG_INVALID_RECIPIENT
	USERFLAG_INVALID_RECIPIENT_WITH_INVITE
	USERFLAG_INVALID_AMOUNT
	USERFLAG_INCORRECTPIN
	USERFLAG_VALIDPIN
	USERFLAG_ALLOW_UPDATE
	USERFLAG_SINGLE_EDIT
	USERFLAG_INCORRECTDATEFORMAT
)
